name: Java CI

on:
    push:
        branches: [ master ]
        tags:
            - 'v*'
            
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
            mvn -B package --file ./plugin/pom.xml
            mkdir staging && cp plugin/target/*.jar staging
            
      - uses: avides/actions-project-version-check@v1.4.0
        id: actions_project_version_check
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            file-to-check: pom.xml
            
      - name: use-version-from-check
        run: echo "New version is:" ${{ steps.actions_project_version_check.outputs.version }}

      - uses: actions/upload-artifact@v3
        with:
          name: MagicznaKraina-v${{ env.RELEASE_VERSION }}
          path: staging
