name: Java CI

on:
    push:
        branches: [ master ]
        tags:
            - 'v*'
            
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Get Commit Data
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Build with Maven
        run: mvn -B package --file ./plugin/pom.xml
#         run: mvn clean package
        
      - run: mkdir output && cp target/*.jar output

      - uses: actions/upload-artifact@v3
        with:
          name: MagicznaKraina-${{ steps.commit.outputs.short }}.zip
          path: output
