name: Java CI

on:
    push:
        branches: [ master ]
        tags:
            - 'v*'
            
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
            mvn -B package --file ./plugin/pom.xml
            mkdir staging && cp plugin/target/*.jar staging
            
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
        

      - uses: actions/upload-artifact@v3
        with:
          name: MagicznaKraina-v${{ steps.project.outputs.version }}
          path: staging
