name: Java CI

on:
    push:
        branches: [ master ]
        tags:
            - 'v*'
            
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
            mvn -B package --file ./plugin/pom.xml
            mkdir staging && cp plugin/target/*.jar staging
            
      - name: Set Release version env variable
        run: |
            echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        

      - uses: actions/upload-artifact@v3
        with:
          name: MagicznaKraina-v${{ env.RELEASE_VERSION }}
          path: staging
