name: Java CI

on:
    push:
        branches: [ master ]
        tags:
            - 'v*'
            
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
            mvn -B package --file ./plugin/pom.xml
            mkdir staging && cp plugin/target/original-*.jar staging/MagicznaKraina.jar
            
      - name: Get project version
        uses: avides/actions-project-version-check@v1.4.0
        id: actions_project_version_check
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            file-to-check: plugin/pom.xml
            only-return-version: true
            
      - name: Display version (debug)
        run: echo "New version is:" ${{ steps.actions_project_version_check.outputs.version }}

      - name: Upload jar file as .zip
        uses: actions/upload-artifact@v3
        with:
          name: MagicznaKraina-v${{ steps.actions_project_version_check.outputs.version }}
          path: |
            staging/MagicznaKraina.jar
            LICENSE
